# Generated by Django 3.2 on 2021-04-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='download',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
