# Generated by Django 3.2 on 2021-04-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0002_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='play',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='playapp.play'),
            preserve_default=False,
        ),
    ]
